name: Publish Python Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["tqdm"]
    steps:
      - uses: actions/checkout@v2
      - id: github-tag-action
        uses: tignis/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Build whl
        env:
          PIP_EXTRA_INDEX_URL: ${{ secrets.PIP_EXTRA_INDEX_URL }}
        id: build-whl
        run: |
          pip wheel -w wheels ./${{ matrix.package }}
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: wheels/${{ matrix.package }}-*.whl
  github:
    name: "Tagged Github Release"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        package: ["tqdm"]
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: set BRANCH if not pull request
        if: github.event_name != 'pull_request'
        run:
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >>
          $GITHUB_ENV
      - name: set BRANCH if pull request
        if: github.event_name == 'pull_request'
        run: echo "BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
      - name: Download wheel
        uses: actions/download-artifact@v4.1.7
        with:
          name: wheel
      - name: add aritfacts to release
        uses: "tignis/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{needs.build.outputs.tag}}
          prerelease: false
          title: "Release ${{needs.build.outputs.tag}}"
          files: |
            ${{ matrix.package }}-*.whl
